name: Build
on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
            sudo apt update
            sudo apt install python3 git ninja-build libsdl2-dev nasm gcc-multilib qemu-system-x86
            sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)" llvm 16

      - name: Set up the build environment
        run: ./skift.sh setup && ./skift.sh doctor

      - name: Download third-party dependencies
        run: ./skift.sh install

      - name: Build Kernel (x86_64)
        run: ./skift.sh build --target=kernel-x86_64

      - name: Build EFI (x86_64)
        run: ./skift.sh build --target=efi-x86_64

      - name: Build Userspace (x86_64)
        run: ./skift.sh build --target=skift-x86_64

      - name: Build Userspace (Host)
        run: ./skift.sh build

      - name: Test Userspace (Host)
        run: ./skift.sh test
